layout_spectrum: 0.2638298
color:
  saturation: 0.3167647
  lightness: 0.6614415
  brandStrength: 0.09417541
  rhythmicContrast: 0.4059665
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.1767083
name: Sammy Aboutalib
